import './styles.css';
import { go, toast } from './ui/shell.js';
import './ui/screens/title.js';
import './ui/screens/scan.js';
import './ui/screens/reveal.js';
import './ui/screens/codex.js';
import './ui/screens/meta.js';
import { warmModel } from './ui/screens/scan.js';
import { state, touchStreak } from './game/state.js';
import { ensureDailyQuests } from './game/quests.js';
import { bindRarity, checkAchievements } from './game/achievements.js';
import { WONDERS } from './data/wonders.js';
import { streakMultiplier } from './game/balance.js';

bindRarity(l => WONDERS[l]?.rarity ?? 0);
const st = touchStreak();
ensureDailyQuests();
checkAchievements();
go('title');
warmModel();
if (st.extended && st.days >= 2) setTimeout(() => toast(`🔥 ${st.days}일 연속 출석! 오늘 XP ×${streakMultiplier(st.days).toFixed(1)}`, 3500), 600);
if (location.search.includes('debug')) window.__ws = { state, go };
